# Generated by Django 4.2.16 on 2026-04-18 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('visibility', models.CharField(choices=[('all', 'All Staff'), ('admin', 'HR Admins Only'), ('supervisors', 'Supervisors & Above'), ('employees', 'Employees Only')], default='all', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notice_attachments/')),
                ('is_active', models.BooleanField(default=True)),
                ('publish_date', models.DateField(default=django.utils.timezone.localdate)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notices',
                'ordering': ['-priority', '-publish_date'],
                'indexes': [models.Index(fields=['is_active', 'visibility'], name='notices_is_acti_3fd8e4_idx'), models.Index(fields=['publish_date', 'expiry_date'], name='notices_publish_901cce_idx')],
            },
        ),
    ]
